#!/usr/bin/env python3
"""Build a standalone distributable package using PyInstaller,
then generate an Inno Setup script for a proper Windows installer
(no admin required, desktop shortcut)."""

import subprocess
import sys
import os
import textwrap


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    os.chdir(script_dir)

    # Ensure example files exist
    print("Generating example files…")
    subprocess.run([sys.executable, "create_examples.py"], check=True)

    print("Running PyInstaller…")
    icon_path = os.path.join(script_dir, "icon.ico")
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--name", "QCert",
        "--noconfirm",
        "--windowed",          # no console window on Windows
        "--add-data", f"examples{os.pathsep}examples",
        "--add-data", f"layouts{os.pathsep}layouts",
        "--add-data", f"fonts{os.pathsep}fonts",
        *(["--icon", icon_path] if os.path.isfile(icon_path) else []),
        "run_qcert.py",
    ]
    subprocess.run(cmd, check=True)

    # Generate Inno Setup script
    _write_inno_script(script_dir)

    print()
    print("Build complete!  Distributable folder: dist/QCert/")
    print()
    print("To create a Windows installer:")
    print("  1. Install Inno Setup from https://jrsoftware.org/isinfo.php")
    print("  2. Open  installer/QCert_setup.iss  in Inno Setup")
    print("  3. Click Build → Compile (or press Ctrl+F9)")
    print("  4. The installer will be created at  installer/QCert_Setup.exe")
    print()
    print("The installer requires NO admin permissions and creates a desktop shortcut.")


def _write_inno_script(project_root: str):
    """Generate an Inno Setup .iss file for QCert."""
    installer_dir = os.path.join(project_root, "installer")
    os.makedirs(installer_dir, exist_ok=True)

    dist_dir = os.path.join(project_root, "dist", "QCert").replace("/", "\\")
    ico_file = os.path.join(project_root, "icon.ico").replace("/", "\\")
    has_icon = os.path.isfile(os.path.join(project_root, "icon.ico"))

    # Inno Setup icon lines (only if icon.ico exists)
    setup_icon_line = f"\n        SetupIconFile={ico_file}" if has_icon else ""
    ico_files_line = (f'Source: "{ico_file}"; DestDir: "{{{{app}}}}"; '
                      f'Flags: ignoreversion') if has_icon else ""
    ico_shortcut = '; IconFilename: "{{app}}\\icon.ico"' if has_icon else ""

    iss_content = textwrap.dedent(f"""\
        ; QCert Inno Setup Script — auto-generated by build.py
        ; Install without admin permissions, creates desktop shortcut.

        [Setup]
        AppName=QCert
        AppVersion=1.0
        AppPublisher=QCert
        DefaultDirName={{userpf}}\\QCert
        DefaultGroupName=QCert
        OutputDir={installer_dir.replace("/", chr(92))}
        OutputBaseFilename=QCert_Setup
        Compression=lzma2
        SolidCompression=yes
        PrivilegesRequired=lowest
        UninstallDisplayName=QCert — Certificate Generator{setup_icon_line}

        [Files]
        Source: "{dist_dir}\\*"; DestDir: "{{app}}"; Flags: recursesubdirs ignoreversion
        {ico_files_line}

        [Icons]
        Name: "{{userdesktop}}\\QCert"; Filename: "{{app}}\\QCert.exe"; WorkingDir: "{{app}}"{ico_shortcut}
        Name: "{{group}}\\QCert"; Filename: "{{app}}\\QCert.exe"; WorkingDir: "{{app}}"{ico_shortcut}
        Name: "{{group}}\\Uninstall QCert"; Filename: "{{uninstallexe}}"

        [Run]
        Filename: "{{app}}\\QCert.exe"; Description: "Launch QCert"; Flags: nowait postinstall skipifsilent
    """)

    iss_path = os.path.join(installer_dir, "QCert_setup.iss")
    with open(iss_path, "w", encoding="utf-8") as f:
        f.write(iss_content)
    print(f"  Created {iss_path}")


if __name__ == "__main__":
    main()
